steps:
  # Paso 1: Instalar todas las dependencias de una vez y descargar data.json
  - name: "python:3.11"
    id: "download-data"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests --break-system-packages
        python download_data.py
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]

  # Paso 2: Ejecutar scripts según la variable _SCRIPTS
  - name: "python:3.11"
    id: "run-scripts"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Scripts a ejecutar: ${_SCRIPTS}"
        IFS=',' read -ra SCRIPT_ARRAY <<< "${_SCRIPTS}"
        for script_num in "${SCRIPT_ARRAY[@]}"; do
          echo "Ejecutando script $script_num"
          case $script_num in
            1) python 1_obtenerurls.py || exit 1 ;;
            2) python 2_extraerinfovideospotenciales.py || exit 1 ;;
            3) python 3_notificar_descartados.py || exit 1 ;;
            4) 
              if [ -n "${_TELEGRAM_IDS}" ]; then
                python 4_cambiar_status.py "${_TELEGRAM_IDS}" || exit 1
              else
                echo "Script 4 omitido: no hay IDs"
              fi
              ;;
            5) python 5_limpiar_no_seleccionados.py || exit 1 ;;
          esac
        done
        echo "Scripts completados"
    env:
      - "TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN}"
      - "TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}"
    # Aquí pasamos ambos secretos como variables de entorno
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS", "OPENAI_API_KEY"]
    waitFor: ["download-data"]

  # Paso 3: Subir data.json actualizado
  - name: "python:3.11"
    id: "upload-data"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        python upload_data.py
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
    waitFor: ["run-scripts"]

# Configuración de Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_DRIVE_CREDENTIALS/versions/latest
      env: "GOOGLE_DRIVE_CREDENTIALS"
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: "OPENAI_API_KEY"

substitutions:
  _SCRIPTS: "1,2,3"
  _TELEGRAM_IDS: ""
  _TELEGRAM_BOT_TOKEN: "8088691958:AAHrOjGVJrvOgbU30rLY23HPmrrNNKYHDUo"
  _TELEGRAM_CHAT_ID: "8088691958"

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: "ALLOW_LOOSE"
  dynamicSubstitutions: true
  machineType: "UNSPECIFIED"