# Paso 2: Ejecutar scripts según la variable _SCRIPTS
  - name: "python:3.11"
    id: "run-scripts"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Instalar ffmpeg
        apt-get update && apt-get install -y ffmpeg
        
        pip install -r requirements.txt --break-system-packages
        echo "Scripts a ejecutar: ${_SCRIPTS}"
        IFS=',' read -ra SCRIPT_ARRAY <<< "${_SCRIPTS}"
        for script_num in "${SCRIPT_ARRAY[@]}"; do
          echo "Ejecutando script $script_num"
          case $script_num in
            1) python 1_obtenerurls.py || exit 1 ;;
            2) python 2_extraerinfovideospotenciales.py || exit 1 ;;
            3) python 3_notificar_descartados.py || exit 1 ;;
            4) 
              if [ -n "${_TELEGRAM_IDS}" ]; then
                python 4_cambiar_status.py "${_TELEGRAM_IDS}" || exit 1
              else
                echo "Script 4 omitido: no hay IDs"
              fi
              ;;
            5) python 5_limpiar_no_seleccionados.py || exit 1 ;;
            6)
              if [ -n "${_VIDEO_ELEGIDO}" ]; then
                python 6_elegir_video.py "${_VIDEO_ELEGIDO}" || exit 1
              else
                echo "Script 6 omitido: no hay ID/URL del video elegido"
              fi
              ;;
            7) python 7_elegir_con_ia.py || exit 1 ;;
            8) python 8_seleccionar_no_shorts.py || exit 1 ;;
            9) python 9_analizar_video.py || exit 1 ;;
            10) python 10_detectar_marcos.py || exit 1 ;;
            11) python 11_recortar_marcos.py || exit 1 ;;
            12) python 12_detectar_logo.py || exit 1 ;;
            13) python 13_recortar_logo.py || exit 1 ;;
            14) python 14_miniatura_final.py || exit 1 ;;
          esac
        done
        echo "Scripts completados"
    env:
      - "TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN}"
      - "TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}"
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS", "OPENAI_API_KEY"]
    waitFor: ["download-data"]