steps:
  # Instalar dependencias Google Drive primero
  - name: "python:3.11"
    entrypoint: "pip"
    args:
      - "install"
      - "google-auth==2.23.4"
      - "google-auth-oauthlib==1.1.0"
      - "google-auth-httplib2==0.1.1"
      - "google-api-python-client==2.108.0"
      - "requests==2.31.0"
      - "--break-system-packages"
    id: "install-google-deps"

  # Instalar resto de dependencias
  - name: "python:3.11"
    entrypoint: "pip"
    args:
      - "install"
      - "-r"
      - "requirements.txt"
      - "--break-system-packages"
    id: "install-deps"
    waitFor: ["install-google-deps"]

  # Descargar data.json desde Google Drive
  - name: "python:3.11"
    entrypoint: "python"
    args: ["download_data.py"]
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
    id: "download-data"
    waitFor: ["install-deps"]

  # Ejecutar scripts según _SCRIPTS variable
  - name: "python:3.11"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        IFS=',' read -ra SCRIPT_ARRAY <<< "${_SCRIPTS}"
        for script_num in "${SCRIPT_ARRAY[@]}"; do
          case $script_num in
            1) python 1_obtenerurls.py ;;
            2) python 2_extraerinfovideospotenciales.py ;;
            3) python 3_notificar_descartados.py ;;
            4) 
              if [ -n "${_TELEGRAM_IDS}" ]; then
                python 4_cambiar_status.py "${_TELEGRAM_IDS}"
              fi
              ;;
            5) python 5_limpiar_no_seleccionados.py ;;
          esac
        done
    env:
      - "TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN}"
      - "TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}"
    id: "run-scripts"
    waitFor: ["download-data"]

  # Subir data.json actualizado a Google Drive
  - name: "python:3.11"
    entrypoint: "python"
    args: ["upload_data.py"]
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
    id: "upload-data"
    waitFor: ["run-scripts"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_DRIVE_CREDENTIALS/versions/latest
      env: "GOOGLE_DRIVE_CREDENTIALS"

substitutions:
  _SCRIPTS: "1,2,3"
  _TELEGRAM_IDS: ""
  _TELEGRAM_BOT_TOKEN: "8088691958:AAHrOjGVJrvOgbU30rLY23HPmrrNNKYHDUo"
  _TELEGRAM_CHAT_ID: "8088691958"

options:
  logging: LEGACY
  machineType: "N1_HIGHCPU_8"