steps:
  # Instalar dependencias
  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    id: 'install-deps'

  # Descargar data.json desde Google Drive
  - name: 'python:3.11'
    entrypoint: 'python'
    args:
      - '-c'
      - |
        import os
        import json
        from google.oauth2.service_account import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaIoBaseDownload
        import io
        
        folder_id = "1-NXHDM29JFrNpzVxMFmfFLMMaNgy44ML"
        credentials_json = os.environ.get('GOOGLE_DRIVE_CREDENTIALS')
        
        if credentials_json:
            credentials_info = json.loads(credentials_json)
            credentials = Credentials.from_service_account_info(
                credentials_info, 
                scopes=['https://www.googleapis.com/auth/drive']
            )
            
            service = build('drive', 'v3', credentials=credentials)
            
            # Buscar data.json
            results = service.files().list(
                q=f"'{folder_id}' in parents and name='data.json' and trashed=false",
                fields="files(id,name)"
            ).execute()
            
            files = results.get('files', [])
            
            if files:
                file_id = files[0]['id']
                request = service.files().get_media(fileId=file_id)
                
                with open('data.json', 'wb') as f:
                    downloader = MediaIoBaseDownload(f, request)
                    done = False
                    while not done:
                        status, done = downloader.next_chunk()
                
                print("✅ data.json descargado")
            else:
                print("⚠️ data.json no encontrado, creando nuevo")
                with open('data.json', 'w') as f:
                    json.dump([], f)
        else:
            print("❌ Credenciales no configuradas")
    secretEnv: ['GOOGLE_DRIVE_CREDENTIALS']
    id: 'download-data'
    waitFor: ['install-deps']

  # Ejecutar scripts según SCRIPTS variable
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SCRIPTS="${_SCRIPTS}"
        TELEGRAM_IDS="${_TELEGRAM_IDS}"
        
        IFS=',' read -ra SCRIPT_ARRAY <<< "$SCRIPTS"
        
        for script_num in "${SCRIPT_ARRAY[@]}"; do
          case $script_num in
            1)
              echo "🚀 Ejecutando script 1: Obtener URLs"
              python 1_obtenerurls.py
              ;;
            2)
              echo "🤖 Ejecutando script 2: Extraer info con IA"
              python 2_extraerinfovideospotenciales.py
              ;;
            3)
              echo "📱 Ejecutando script 3: Notificar a Telegram"
              python 3_notificar_descartados.py
              ;;
            4)
              echo "✏️ Ejecutando script 4: Cambiar status"
              if [ -n "$TELEGRAM_IDS" ]; then
                python 4_cambiar_status.py "$TELEGRAM_IDS"
              else
                echo "⚠️ No se proporcionaron IDs de Telegram"
              fi
              ;;
            5)
              echo "🧹 Ejecutando script 5: Limpiar no seleccionados"
              python 5_limpiar_no_seleccionados.py
              ;;
            *)
              echo "⚠️ Script $script_num no reconocido"
              ;;
          esac
        done
    id: 'run-scripts'
    waitFor: ['download-data']

  # Subir data.json actualizado a Google Drive
  - name: 'python:3.11'
    entrypoint: 'python'
    args:
      - '-c'
      - |
        import os
        import json
        from google.oauth2.service_account import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
        
        folder_id = "1-NXHDM29JFrNpzVxMFmfFLMMaNgy44ML"
        credentials_json = os.environ.get('GOOGLE_DRIVE_CREDENTIALS')
        
        if credentials_json:
            credentials_info = json.loads(credentials_json)
            credentials = Credentials.from_service_account_info(
                credentials_info, 
                scopes=['https://www.googleapis.com/auth/drive']
            )
            
            service = build('drive', 'v3', credentials=credentials)
            
            # Buscar si existe data.json
            results = service.files().list(
                q=f"'{folder_id}' in parents and name='data.json' and trashed=false",
                fields="files(id)"
            ).execute()
            
            files = results.get('files', [])
            
            media = MediaFileUpload('data.json', mimetype='application/json')
            
            if files:
                # Actualizar archivo existente
                file_id = files[0]['id']
                service.files().update(
                    fileId=file_id,
                    media_body=media
                ).execute()
                print("✅ data.json actualizado en Google Drive")
            else:
                # Crear nuevo archivo
                file_metadata = {
                    'name': 'data.json',
                    'parents': [folder_id]
                }
                service.files().create(
                    body=file_metadata,
                    media_body=media,
                    fields='id'
                ).execute()
                print("✅ data.json creado en Google Drive")
        else:
            print("❌ Credenciales no configuradas")
    secretEnv: ['GOOGLE_DRIVE_CREDENTIALS']
    id: 'upload-data'
    waitFor: ['run-scripts']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_DRIVE_CREDENTIALS/versions/latest
      env: 'GOOGLE_DRIVE_CREDENTIALS'

substitutions:
  _SCRIPTS: '1,2,3'  # Scripts a ejecutar separados por coma
  _TELEGRAM_IDS: ''   # IDs de videos para script 4 (vacío por defecto)

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'