steps:
  # Paso 1: Instalar dependencias y descargar data.json
  - name: "python:3.11"
    id: "download-data"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt --break-system-packages
        python download_data.py
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
  
  # Paso 2: Ejecutar scripts según la variable _SCRIPTS
  - name: "python:3.11"
    id: "run-scripts"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt --break-system-packages
        echo "Scripts a ejecutar: ${_SCRIPTS}"
        IFS=',' read -ra SCRIPT_ARRAY <<< "${_SCRIPTS}"
        for script_num in "${SCRIPT_ARRAY[@]}"; do
          echo "Ejecutando script $script_num"
          case $script_num in
            1) python 1_obtenerurls.py || exit 1 ;;
            2) python 2_extraerinfovideospotenciales.py || exit 1 ;;
            3) python 3_notificar_descartados.py || exit 1 ;;
            4) 
              if [ -n "${_TELEGRAM_IDS}" ]; then
                python 4_cambiar_status.py "${_TELEGRAM_IDS}" || exit 1
              else
                echo "Script 4 omitido: no hay IDs"
              fi
              ;;
            5) python 5_limpiar_no_seleccionados.py || exit 1 ;;
            6)
              if [ -n "${_VIDEO_ELEGIDO}" ]; then
                python 6_elegir_video.py "${_VIDEO_ELEGIDO}" || exit 1
              else
                echo "Script 6 omitido: no hay ID/URL del video elegido"
              fi
              ;;
            7) python 7_elegir_con_ia.py || exit 1 ;;
            8) python 8_seleccionar_no_shorts.py || exit 1 ;;
            9) python 9_analizar_video.py || exit 1 ;;
            10) python 10_detectar_marcos.py || exit 1 ;;
            11) python 11_recortar_marcos.py || exit 1 ;;
            12) python 12_detectar_logo.py || exit 1 ;;
            13) python 13_recortar_logo.py || exit 1 ;;
            14) python 14_miniatura_final.py || exit 1 ;;
          esac
        done
        echo "Scripts completados"
    env:
      - "TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN}"
      - "TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}"
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS", "OPENAI_API_KEY"]
    waitFor: ["download-data"]
  
  # Paso 3: Subir archivos actualizados
  - name: "python:3.11"
    id: "upload-data"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt --break-system-packages
        python upload_data.py
        # Subir archivos generados
        for file in descargar.json registro.json marcos.json logo.json miniatura_final.jpg; do
          if [ -f "$file" ]; then
            python upload_file.py "$file" || true
          fi
        done
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
    waitFor: ["run-scripts"]

# Configuración de Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_DRIVE_CREDENTIALS/versions/latest
      env: "GOOGLE_DRIVE_CREDENTIALS"
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: "OPENAI_API_KEY"

# Variables de sustitución
substitutions:
  _SCRIPTS: "1,2,3"  # Combos disponibles (ver abajo)
  _TELEGRAM_IDS: ""
  _VIDEO_ELEGIDO: ""
  _TELEGRAM_BOT_TOKEN: "8599691958:AAHrOjGVJrvOgbU30rLY23HPmrrNNKYHDUs"
  _TELEGRAM_CHAT_ID: "6166225652"

# COMBOS DISPONIBLES:
# "1,2,3" - Básico: obtener URLs, extraer info, notificar
# "1,2,3,7" - Básico + IA: incluye selección automática con IA
# "1,2,3,5" - Básico + limpieza: incluye limpiar no seleccionados
# "1,2,3,5,7" - Básico + limpieza + IA
# "1,2,3,5,6" - Básico + limpieza + elegir video manual
# "1,8" - URLs + seleccionar no shorts
# "1,8,7" - URLs + no shorts + IA
# "9,10,11,12,13,14" - Pipeline completo de miniatura
# "1,2,3,5,7,9,10,11,12,13,14" - COMPLETO: análisis + miniatura

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: "ALLOW_LOOSE"
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_8"  # Necesario para Vision/Video APIs