steps:
  # Instalar dependencias
  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', '--user']
    id: 'install-deps'

  # Descargar data.json desde Google Drive
  - name: 'python:3.11'
    entrypoint: 'python'
    args: ['download_data.py']
    secretEnv: ['GOOGLE_DRIVE_CREDENTIALS']
    id: 'download-data'
    waitFor: ['install-deps']

  # Ejecutar scripts según _SCRIPTS variable
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IFS=',' read -ra SCRIPT_ARRAY <<< "${_SCRIPTS}"
        
        for script_num in "$${SCRIPT_ARRAY[@]}"; do
          case $$script_num in
            1)
              echo "🚀 Ejecutando script 1: Obtener URLs"
              python 1_obtenerurls.py
              ;;
            2)
              echo "🤖 Ejecutando script 2: Extraer info con IA"
              python 2_extraerinfovideospotenciales.py
              ;;
            3)
              echo "📱 Ejecutando script 3: Notificar a Telegram"
              python 3_notificar_descartados.py
              ;;
            4)
              echo "✏️ Ejecutando script 4: Cambiar status"
              if [ -n "${_TELEGRAM_IDS}" ]; then
                python 4_cambiar_status.py "${_TELEGRAM_IDS}"
              else
                echo "⚠️ No se proporcionaron IDs de Telegram"
              fi
              ;;
            5)
              echo "🧹 Ejecutando script 5: Limpiar no seleccionados"
              python 5_limpiar_no_seleccionados.py
              ;;
            *)
              echo "⚠️ Script $$script_num no reconocido"
              ;;
          esac
        done
    env:
      - 'TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN}'
      - 'TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}'
    id: 'run-scripts'
    waitFor: ['download-data']

  # Subir data.json actualizado a Google Drive
  - name: 'python:3.11'
    entrypoint: 'python'
    args: ['upload_data.py']
    secretEnv: ['GOOGLE_DRIVE_CREDENTIALS']
    id: 'upload-data'
    waitFor: ['run-scripts']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_DRIVE_CREDENTIALS/versions/latest
      env: 'GOOGLE_DRIVE_CREDENTIALS'

substitutions:
  _SCRIPTS: '1,2,3'
  _TELEGRAM_IDS: ''
  _TELEGRAM_BOT_TOKEN: '8599691958:AAHrOjGVJrvOgbU30rLY23HPmrrNNKYHDU'
  _TELEGRAM_CHAT_ID: '8599691958'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'