# Configuración global
timeout: "3600s"

steps:
  # Paso 1: Instalar dependencias y descargar data inicial
  - name: "python:3.11"
    id: "download-data"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt --break-system-packages --no-cache-dir
        python download_data.py
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
  
  # Paso 2: Ejecutar scripts en combo con SINCRONIZACIÓN INMEDIATA
  - name: "python:3.11"
    id: "run-scripts"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt --break-system-packages --no-cache-dir
        echo "Scripts a ejecutar: ${_SCRIPTS}"
        IFS=',' read -ra SCRIPT_ARRAY <<< "${_SCRIPTS}"
        for script_num in "${SCRIPT_ARRAY[@]}"; do
          echo ">>> Ejecutando script $script_num"
          case $script_num in
            1) python 1_obtenerurls.py && python upload_data.py || exit 1 ;;
            2) python 2_extraerinfovideospotenciales.py && python upload_data.py || exit 1 ;;
            3) python 3_notificar_descartados.py && python upload_data.py || exit 1 ;;
            4) 
              if [ -n "${_TELEGRAM_IDS}" ]; then
                python 4_cambiar_status.py "${_TELEGRAM_IDS}" && python upload_data.py || exit 1
              fi ;;
            5) python 5_limpiar_no_seleccionados.py && python upload_data.py || exit 1 ;;
            6)
              if [ -n "${_VIDEO_ELEGIDO}" ]; then
                python 6_elegir_video.py "${_VIDEO_ELEGIDO}" && python upload_data.py || exit 1
              fi ;;
            7) python 7_elegir_con_ia.py && python upload_data.py || exit 1 ;;
            8) python 8_seleccionar_no_shorts.py && python upload_data.py || exit 1 ;;
            9) python 9_analizar_video.py && python upload_data.py || exit 1 ;;
            10) 
              python 10_sacar_imagenes.py && python upload_data.py
              for i in {1..10}; do [ -f "imagen$i.jpg" ] && python upload_file.py "imagen$i.jpg"; done ;;
            11) python 11_detectar_marcos.py && python upload_data.py && [ -f "marcos.json" ] && python upload_file.py "marcos.json" ;;
            12) python 12_recortar_marcos.py && python upload_data.py || exit 1 ;;
            13) python 13_detectar_logo.py && python upload_data.py && [ -f "logo.json" ] && python upload_file.py "logo.json" ;;
            14) python 14_recortar_logo.py && python upload_data.py || exit 1 ;;
            15) python 15_miniatura_final.py && python upload_data.py && [ -f "miniatura_final.jpg" ] && python upload_file.py "miniatura_final.jpg" ;;
            16) python 16_cambio_nombres_imagenes_y_video.py && python upload_data.py || exit 1 ;;
            17) python 17_renombrar_imagenes.py && python upload_data.py || exit 1 ;;
          esac
          echo ">>> Script $script_num completado y sincronizado con Drive"
        done
    env:
      - "TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN}"
      - "TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}"
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS", "OPENAI_API_KEY"]
    waitFor: ["download-data"]
  
  # Paso 3: Subida final de seguridad
  - name: "python:3.11"
    id: "upload-data"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt --break-system-packages --no-cache-dir
        python upload_data.py
        for file in descargar.json subidos.json registro.json marcos.json logo.json miniatura_final.jpg imagen1.jpg imagen2.jpg imagen3.jpg imagen4.jpg imagen5.jpg imagen6.jpg imagen7.jpg imagen8.jpg imagen9.jpg imagen10.jpg; do
          if [ -f "$file" ]; then python upload_file.py "$file" || true; fi
        done
    secretEnv: ["GOOGLE_DRIVE_CREDENTIALS"]
    waitFor: ["run-scripts"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_DRIVE_CREDENTIALS/versions/latest
      env: "GOOGLE_DRIVE_CREDENTIALS"
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: "OPENAI_API_KEY"

substitutions:
  _SCRIPTS: "1,2,3"
  _TELEGRAM_IDS: ""
  _VIDEO_ELEGIDO: ""
  _TELEGRAM_BOT_TOKEN: "8599691958:AAHrOjGVJrvOgbU30rLY23HPmrrNNKYHDUs"
  _TELEGRAM_CHAT_ID: "6166225652"

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: "ALLOW_LOOSE"
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_8"